@startuml
left to right direction
skinparam packageStyle rectangle

actor Домовладелец
actor Администратор

rectangle "Система управления освещением" {
  usecase "Настройка расписания освещения" as UC1
  usecase "Управление освещением голосом" as UC2
  usecase "Управление освещением через мобильное приложение" as UC3
  usecase "Создание сценария освещения" as UC4
}

rectangle "Система управления климатом" {
  usecase "Настройка значений температуры" as UC5
  usecase "Создание сценария охлаждения" as UC6
  usecase "Управление кондиционером голосом" as UC7
  usecase "Управление кондиционером через приложение" as UC8
}

rectangle "Утренний подъём" {
   usecase "Наcтройка будильника" as UC9
   usecase "Синхронизация будильника и штор" as  UC10
   usecase "Выключение будильника голосом" as UC11
   usecase "Управление шторами голосом" as UC12
   usecase "Управление шторами через приложение" as UC13
}


Администратор --> UC1
Домовладелец --> UC2
Домовладелец --> UC3
Домовладелец --> UC4
Домовладелец --> UC5
Администратор --> UC6
Домовладелец --> UC7
Домовладелец --> UC8
Домовладелец --> UC9
Администратор --> UC10
Домовладелец --> UC11
Домовладелец --> UC12
Домовладелец --> UC13
@enduml