@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Контекстная диаграмма (C4): Система управления умным домом на BPMN/MQTT

Person(Пользователь, "Домовладелец", "Управляет устройствами через приложение/голосовые команды")
Person(Администратор, "Администратор", "Мониторинг состояния устройств, обработка сбоев")
Person(Разработчик, "Разработчик IoT", "Гибкий API для интеграции новых устройств, отладка процессов")

System(УмныйДом, "Умный дом (BPMN + MQTT)", "Camunda + Mosquitto", "Оркестрация процессов автоматизации")

System_Ext(IoT_устройства, "IoT-устройства", "Датчики, реле, кондиционеры")
System_Ext(ВнешниеСервисы, "Внешние сервисы", "Алиса, погодные API")

Rel(Пользователь, УмныйДом, "Отправляет команды", "REST/Web/MQTT")
Rel(УмныйДом, IoT_устройства, "Чтение данных/управление", "MQTT (home/+/status, home/+/control)")
Rel(УмныйДом, ВнешниеСервисы, "Интеграция с голосовыми ассистентами", "REST API")
Rel(IoT_устройства, УмныйДом, "Отправка событий", "MQTT (home/sensor/temp, home/light/status)")
Rel(Администратор, УмныйДом, "Мониторинг состояния датчиков", "Дашборды")
Rel(Администратор, IoT_устройства, "Проверка устройств", "Физически")
Rel(Разработчик, УмныйДом, "Внесение изменений в процесс", "BPMN-editor")


@enduml